[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class=dropterm"
# command = "ghostty --class=dropterm"
class = "dropterm"
size = "75% 60%"
